services:
  api:
    image: api
    build: .
    container_name: nocodeapi
    ports:
      - "8080:8080"
      - "9000:9000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://nocodeapidb:5432/nocodeapidb
      - SPRING_DATASOURCE_USERNAME=nocodeapiowner
      - SPRING_DATASOURCE_PASSWORD=nocodeapiowner
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - api-network
      - system_api-network

  db:
    image: postgres:16.4-alpine
    container_name: nocodeapidb
    environment:
      - POSTGRES_DB=nocodeapidb
      - POSTGRES_USER=nocodeapiowner
      - POSTGRES_PASSWORD=nocodeapiowner
    ports:
      - "35432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - system_api-network

networks:
  system_api-network:
    external: true
  api-network:
    driver: bridge

volumes:
  postgres_data:
