spring.application.name=nocodeapi

spring.datasource.url=jdbc:postgresql://localhost:35432/nocodeapidb
spring.datasource.username=nocodeapiowner
spring.datasource.password=nocodeapiowner

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.flyway.out-of-order=true

rsa.private-key=classpath:certs/private.pem
rsa.public-key=classpath:certs/public.pem