spring.application.name=nocodeapi

spring.datasource.url=jdbc:postgresql://localhost:35432/nocodeapidb
spring.datasource.username=nocodeapiowner
spring.datasource.password=nocodeapiowner

server.address=0.0.0.0

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.out-of-order=true

rsa.private-key=classpath:certs/private.pem
rsa.public-key=classpath:certs/public.pem

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

openai.base-url=https://openrouter.ai/api/v1
openai.api-key=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
openai.model=mistralai/mistral-7b-instruct:free

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config

logging.level.org.springframework.web=DEBUG

spring.security.oauth2.client.registration.auth0.client-id=TcU5RAPYWCUNSJC1BtkRVS9moifYXohr
spring.security.oauth2.client.registration.auth0.client-secret=Vg43Z1kEnWy7OLtJmxEqcGKMCHHDMwsAMZJ3wViC0YEx1H69vsAGCDbTGR7R3r_t
spring.security.oauth2.client.registration.auth0.scope=openid,profile,email
spring.security.oauth2.client.registration.auth0.redirect-uri={baseUrl}/login/oauth2/code/auth0
spring.security.oauth2.client.registration.auth0.authorization-grant-type=authorization_code

spring.security.oauth2.client.provider.auth0.authorization-uri=https://dev-jyepfaxin565wx6f.us.auth0.com/authorize
spring.security.oauth2.client.provider.auth0.token-uri=https://dev-jyepfaxin565wx6f.us.auth0.com/oauth/token
spring.security.oauth2.client.provider.auth0.user-info-uri=https://dev-jyepfaxin565wx6f.us.auth0.com/userinfo
spring.security.oauth2.client.provider.auth0.user-name-attribute=sub
