spring.application.name=nocodeapi

spring.datasource.url=jdbc:postgresql://localhost:35432/nocodeapidb
spring.datasource.username=nocodeapiowner
spring.datasource.password=nocodeapiowner

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.flyway.out-of-order=true

logging.level.org.springframework=DEBUG


rsa.private-key=classpath:certs/private.pem
rsa.public-key=classpath:certs/public.pem

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Enable detailed logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.transaction=DEBUG
logging.level.at.kalwoda.nocodeapi=DEBUG

# Show constraint violations
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=DEBUG